apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: SecurityGroup
metadata:
  name: 'xplanesg'
  labels:
    sgname: 'xplanesg'
spec:
  forProvider:
    name: 'xplane-xplanesg'
    region: 'eu-west-1'
    description: 'xplane SG test'
    vpcId: 'vpc-1234abcd'
  providerConfigRef:
    name: 'aws-jetprovider-config'
