---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: production-routetable
spec:
  forProvider:
    region: us-east-1
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: production-internetgateway
    associations:
      - subnetIdRef:
          name: App-2a
      - subnetIdRef:
          name: Inside-2a
    vpcIdRef:
      name: vpc-0039692d4dfd22c93
  providerConfigRef:
    name: aws-provider-config
